version: "3.9"
services:
  postgres:
    image: postgres:13.3
    volumes:
      - ./:$HOME/lab_src
    environment:
      POSTGRES_DB: "lab_db"
      POSTGRES_USER: "lab_user"
      POSTGRES_PASSWORD: "lab_pwd"
    ports:
      - "5432:5432"
